version: '3'


services:
  redis-db:
    image: redis
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always


volumes:
  redis_data:
    name: redis_data